<a href="https://colab.research.google.com/github/gramelon2003/a/blob/master/BTVN1C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = 5
y = -12
z = 3.1417

In [3]:
x = np.array([2, -1, 3, 6])
print(x.ndim)
print(x.shape)

1
(4,)


In [4]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X)
print(X.ndim)
print(X.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [5]:
X = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((3,2,2))
print(X)
print(X.ndim)
print(X.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [ ]:
from matplotlib import pyplot as plt
img = plt.imread('/content/tải xuống.jpg')
print(img.ndim)
print(img.shape)

3
(126, 168, 3)


In [ ]:
from IPython.display import HTML
from base64 import b64encode
mp4 = open('/content/y2mate.com - Background  lửa cháy_480p.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=400 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)

In [ ]:
import cv2
frames = []

path = "/content/y2mate.com - Background  lửa cháy_480p.mp4"
cap = cv2.VideoCapture(path)
ret = True
while ret:
    ret, img = cap.read() 
    if ret:
        frames.append(img)
video = np.stack(frames, axis=0)
print(video)

[[[[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  ...

  [[ 14 154 218]
   [ 13 153 217]
   [ 11 149 213]
   ...
   [ 13 208 236]
   [ 14 208 232]
   [ 14 208 232]]

  [[ 14 154 218]
   [ 14 154 218]
   [ 12 155 218]
   ...
   [  8 205 233]
   [ 10 211 229]
   [ 10 211 229]]

  [[ 14 154 218]
   [ 14 154 218]
   [ 12 155 218]
   ...
   [  9 206 234]
   [  9 210 228]
   [  9 210 228]]]


 [[[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1   1]]

  [[  1   1   1]
   [  1   1   1]
   [  1   1   1]
   ...
   [  1   1   1]
   [  1   1   1]
   [  1   1

In [ ]:
print(video.shape)

(250, 480, 854, 3)


In [ ]:
print(video.ndim)

4
