<a href="https://colab.research.google.com/github/gramelon2003/a/blob/master/BTVN2C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4])
y=np.array([5,3,2,1])
z=x+y
print(z)
print(z.ndim)
print(z.shape)

[6 5 5 5]
1
(4,)


In [ ]:
x=np.arange(1,8,2)
y=np.arange(10,14,1)
print(x)
print(y)
print(z)
print(z.ndim)
print(z.shape)

[1 3 5 7]
[10 11 12 13]
[6 5 5 5]
1
(4,)


In [ ]:
x=np.array([1,2,3,4])
a = 15
z = a*x
print(z)
print(z.ndim)
print(z.shape)

[15 30 45 60]
1
(4,)


In [ ]:
x= np.arange(2,9,2)
a=10
print(x)
z = a*x
print(z)
print(z.ndim)
print(z.shape)

[2 4 6 8]
[20 40 60 80]
1
(4,)


In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = np.dot(x,y)
print(z)
print(z.ndim)
print(z.shape)

21
0
()


In [ ]:
x= np.arange(11,15,1)
y= np.arange(3,7,1)
z = np.dot(x,y)
print(z)
print(z.ndim)
print(z.shape)

230
0
()


In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.cross(x, y)
print(z)
print(z.ndim)
print(z.shape)

[-4  8 -4]
1
(3,)


In [ ]:
x= np.arange(3,6,1)
y= np.arange(13,16,1)
z = np.cross(x, y)
print(z)
print(z.ndim)
print(z.shape)

[-10  20 -10]
1
(3,)


In [ ]:
x = np.array([1,2,3,4])
y = np.array([5,3,2,1])
z = x*y 
print(z)
print(z.ndim)
print(z.shape)

[5 6 6 4]
1
(4,)


In [ ]:
x=np.random.randint(8, size=4)
y=np.random.randint(8, size=4)
z = x*y 
print(z)
print(z.ndim)
print(z.shape)

[ 0 28  7  2]
1
(4,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = X + Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[7 7 7]
 [7 7 7]]
2 ;  (2, 3)


In [ ]:
x=np.random.randint(8, size=4)
y=np.random.randint(8, size=4)
Z = x + y
print(Z)
print(Z.ndim, '; ', Z.shape)

[5 2 4 7]
1 ;  (4,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
a = 2
Z = a*X
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 2  4  6]
 [ 8 10 12]]
2 ;  (2, 3)


In [ ]:
x=np.random.randint(8, size=4)
a = np.random.randint(10)
Z = a*x
print(Z)
print(Z.ndim, '; ', Z.shape)

[ 8 48 56  8]
1 ;  (4,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Z = X.T
print(Z)
print(Z.ndim, '; ', Z.shape)

[[1 4]
 [2 5]
 [3 6]]
2 ;  (3, 2)


In [ ]:
x=np.random.randint(8, size=4).T
print(x)
print(x.ndim, '; ', x.shape)

[6 7 4 5]
1 ;  (4,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((3,2))
Z = np.dot(X,Y)
print(Z)
print(Z.ndim, '; ', Z.shape)

[[20 14]
 [56 41]]
2 ;  (2, 2)


In [ ]:
x=np.random.randint(8, size=4)
y=np.random.randint(8, size=4)
Z = np.dot(x,y)
print(Z)
print(Z.ndim, '; ', Z.shape)

45
0 ;  ()


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
Y = np.array([6,5,4,3,2,1]).reshape((2,3))
Z = np.multiply(X,Y) #hoặc Z = X*Y
print(Z)
print(Z.ndim, '; ', Z.shape)

[[ 6 10 12]
 [12 10  6]]
2 ;  (2, 3)


In [ ]:
x=np.random.randint(8, size=4)
y=np.random.randint(8, size=4)
Z = x*y
print(Z)
print(Z.ndim, '; ', Z.shape)

[ 0 49 21  0]
1 ;  (4,)


In [ ]:
x = np.array([1,2,3,4,5]).reshape((5,1))
print(x)
print(x.ndim, '; ', x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2 ;  (5, 1)


In [ ]:
y=np.random.randint(8, size=4)
n=len(y)
print(y.reshape(n,1))
print(y.ndim, '; ', y.shape)

[[7]
 [5]
 [3]
 [5]]
1 ;  (4,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[0, :]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((1,n))
print(x)
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[1 2 3]
1 ;  (3,)
[[1 2 3]]
2 ;  (1, 3)


In [ ]:
y=np.random.randint(10, size=9)
n=len(y)
x=y.reshape(n-6,3)
#print(x)
y1=x[:,0]
print(y1)
k=len(y1)
print(y1.reshape(1,k))
print(y1.ndim, '; ', y1.shape)


[8 5 6]
[[8 5 6]]
1 ;  (3,)


In [ ]:
X = np.array([1,2,3,4,5,6]).reshape((2,3))
m = X.shape[0]
n = X.shape[1]
print('m = ', m, '; n = ', n)
x = X[:,1]
print(x)
print(x.ndim, '; ', x.shape)
x = x.reshape((m,1))
print(x)
print(x.ndim, '; ', x.shape)

m =  2 ; n =  3
[2 5]
1 ;  (2,)
[[2]
 [5]]
2 ;  (2, 1)


In [ ]:
y=np.random.randint(10, size=12)
y=y.reshape(4,3)
y=y[:,1]
#print(y)
m=len(y)
print(y.reshape(m,1))

[[2]
 [8]
 [2]
 [4]]


In [ ]:
X =np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((4,3))
x = np.array([1,1,1,1]).reshape((4,1))
X = np.column_stack([x,X])
print(X)
print(X.ndim, '; ', X.shape)

[[ 1  1  2  3]
 [ 1  4  5  6]
 [ 1  7  8  9]
 [ 1 10 11 12]]
2 ;  (4, 4)


In [ ]:
a=np.ones((4,), dtype=int)
#print(a)
y=np.random.randint(10, size=12).reshape(4,3)
x=np.column_stack([a,y])
print(x)

[[1 0 3 9]
 [1 4 5 7]
 [1 4 2 8]
 [1 3 4 5]]


In [ ]:
data = np.array([[10,22,13,1],
[9,6,5,0],
[8,12,4,1],
[6,5,7,0]])
X = data[:,:-1]
y = data[:,-1].reshape((data.shape[0], 1))
print(X)
print(X.ndim, '; ', X.shape)
print(y)
print(y.ndim, '; ', y.shape)

[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)
[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


In [ ]:
y=np.random.randint(10, size=12).reshape(4,3)
print(y)
x=y[:, 0].reshape(4,1)
print(x)
print(x.ndim, '; ', x.shape)
x1=y[:,-1].reshape(4,1)
print(x1)
print(x1.ndim, '; ', x1.shape)


[[5 4 8]
 [9 0 3]
 [7 4 0]
 [5 6 2]]
[[5]
 [9]
 [7]
 [5]]
2 ;  (4, 1)
[[8]
 [3]
 [0]
 [2]]
2 ;  (4, 1)


In [ ]:
data = np.array([[10,22,13,1],
[9,6,5,0],
[8,12,4,1],
[6,5,7,0]])
X = data[:,:-1]
y = data[:,-1].reshape((data.shape[0], 1))
print(X)
print(X.ndim, '; ', X.shape)
print(y)
print(y.ndim, '; ', y.shape)

[[10 22 13]
 [ 9  6  5]
 [ 8 12  4]
 [ 6  5  7]]
2 ;  (4, 3)
[[1]
 [0]
 [1]
 [0]]
2 ;  (4, 1)


In [ ]:
y=np.random.randint(10, size=12).reshape(3,4)
print(y)
print(y.ndim, '; ', y.shape)
y1=y[:,-1].reshape(3,1)
print(y1)
print(y1.ndim, '; ', y1.shape)

[[0 7 2 0]
 [6 8 9 3]
 [8 5 9 8]]
2 ;  (3, 4)
[[0]
 [3]
 [8]]
2 ;  (3, 1)


In [ ]:
import numpy as np
m=2
n=2
k=3
T = np.random.randint(low=-5,
high=5,size=m*n*k).reshape(k,m,n)
print(T)

[[[-3  0]
  [-2 -5]]

 [[ 4  4]
  [-1  0]]

 [[-4 -2]
  [-1  1]]]


In [ ]:
m=2
n=2
k=3
t1 = np.random.randint(low=-5,high=5,size=m*n*k).reshape(k,m,n)
t2 = np.random.randint(low=-5,high=5,size=m*n*k).reshape(k,m,n)
t3 = np.random.randint(low=-5,high=5,size=m*n*k).reshape(k,m,n)
t4 = np.random.randint(low=-5,high=5,size=m*n*k).reshape(k,m,n)
T = np.stack((t1, t2, t3, t4), axis=-1)
print(T)
print(T.shape)
x = T[:,:,:,0]
print(x)
m1 = x[0,:,:]
print(m1)
print(m1.shape)

[[[[-4  4 -5 -3]
   [ 0 -1 -3 -4]]

  [[ 2  1  4 -5]
   [-5 -1  2 -2]]]


 [[[ 2 -2 -3  0]
   [-5 -1 -5 -4]]

  [[-3 -4 -2  1]
   [ 4 -5  3  3]]]


 [[[-4 -1 -3 -3]
   [-5 -4 -1  2]]

  [[ 3 -5  4  3]
   [ 2 -2  1 -5]]]]
(3, 2, 2, 4)
[[[-4  0]
  [ 2 -5]]

 [[ 2 -5]
  [-3  4]]

 [[-4 -5]
  [ 3  2]]]
[[-4  0]
 [ 2 -5]]
(2, 2)


In [ ]:
T1 = np.random.randint(10, size=(2, 2,3)).reshape(3,2,2)
T2 = np.random.randint(10, size=(2, 2,3)).reshape(3,2,2)
T=np.column_stack((T1,T2)).reshape(3,2,2,2)
print(T)
print(T.shape)

[[[[5 0]
   [2 7]]

  [[2 4]
   [1 6]]]


 [[[4 1]
   [0 9]]

  [[3 7]
   [9 0]]]


 [[[2 8]
   [5 3]]

  [[1 3]
   [6 4]]]]
(3, 2, 2, 2)
